application: sridharreddy0007m
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application
- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
